name: benchapp
description: Simple Dart DB performance benchmark

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  objectbox: ^0.11.0
  objectbox_flutter_libs: any
  path_provider: ^1.6.27
  sqflite: ^1.3.0
  path: ^1.7.0
  cupertino_icons: ^0.1.2
  hive: ^1.4.4+1

dev_dependencies:
  objectbox_generator: any
  build_runner: ^1.0.0
  hive_generator: ^0.8.2

#dependency_overrides:
#  objectbox:
#    path: ../objectbox-dart/objectbox
#  objectbox_flutter_libs:
#    path: ../objectbox-dart/flutter_libs
#  objectbox_generator:
#    path: ../objectbox-dart/generator
