name: db_benchmark
description: Simple Dart DB performance benchmark

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  objectbox: any

dev_dependencies:
  objectbox_generator: any
  build_runner: ^1.0.0

dependency_overrides:
  objectbox:
    path: ../objectbox-dart
  objectbox_generator:
    path: ../objectbox-dart/generator
